server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/filesystem?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false

  application:
    name: client-name


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:sqlMapConfig.xml

eureka:
  client:
    fetch-registry: true #是否从eureka服务器获取各个微服务地址
    register-with-eureka: true #是否注册到eureka服务器
    service-url:
      defaultZone: http://localhost:2020/eureka/
